### ISSUE TITLE
Encontro 22

### ISSUE THREAD

**Issue by filipebarcos** [guru-ce/cfp#6]
Issue para linkar os PRs de CFP para o encontro 22.

Data do encontro: 15 de fevereiro de 2017
Data limite para submissão: 31 de janeiro de 2017

Antes de submeter uma proposta, leia https://github.com/guru-ce/cfp/tree/master/palestras

**Comment by gurgelrenan** [comment]
@filipebarcos acho que podemos fechar essa issue não é?

**Comment by gurgelrenan** [comment]
Ou atualizar para:
```
Issue para linkar os PRs de CFP para o encontro 22.

Data do encontro: 31 de outubro de 2017
Data limite para submissão: 27 de outubro de 2017

Antes de submeter uma proposta, leia https://github.com/guru-ce/cfp/tree/master/palestras
```

**Comment by filipebarcos** [comment]
Fecha, cria uma nova. BTW, acho que 27 para 31 pouquíssimo tempo para anunciar o encontro já com os palestrantes. Deixaria pelo menos 1 semana
